name: Publish Package
on:
  release:
    types: [created]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      # Setup .npmrc file to publish to GitHub Packages
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@dobe0002' # Defaults to the user or organization that owns the workflow file
      - name: Install and build
        run: |
          npm install
          npm run build
      - name: Tests
        run: npm run test
      - name: Test coverage
        run: node utils/testCoverage.js
      - name: Linting
        run: npm run eslint
      - name: Security audit
        run: npm run npmAuditJson
      - name: Publish
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN_PUBLISH }}
